### ISSUE TITLE
Silverstripe 5 upgrade

### ISSUE THREAD

**Issue by Sitetools** [octavenz/silverstripe-reoako#10]
Hi @octavenz
We have been asked to add this addon to one of our websites, but we are also in the middle of upgrading to SS5.
Do you have an estimate of when you'll be supporting Silverstripe 5 and / or PHP 8.2?

CC @axllent

Cheers
Robin

**Comment by michalkleiner** [comment]
Looking at the code, I don't see anything that would prevent this working on CMS5 as it is, so it might be as simple as relaxing the Composer constraints.

**Comment by Sitetools** [comment]
That would be excellent - thanks @michalkleiner.

**Comment by michalkleiner** [comment]
Would you want to open a PR to that effect so that others can test it with your fork to see if all works fine?

**Comment by octdanb** [comment]
I have started to look into this today and have discovered due to the TinyMCE 6 upgrade in Silverstripe5 it will require a fair amount of work on our part.

 I will discuss with our team and get back to you on a ETA on a Silverstripe5 release.

**Comment by Sitetools** [comment]
Thanks @octdanb , much appreciated.

**Comment by octdanb** [comment]
@Sitetools  We have a meeting scheduled to discuss this upgrade on thursday, just for context, which website are you planning adding reoako to? are you aware youll need api key access ect?

**Comment by Sitetools** [comment]
@octdanb Yes we have an API key, I am corresponding with you on behalf of Springtimesoft who have a Government related website. We are in the process of adding your application to their website.

**Comment by octdanb** [comment]
@Sitetools 
I have released a prerelease 1.0.0 version of the plugin which now includes initial support for Silverstripe5.
Silverstripe 4 releases will continue on the 0.x.x tag range.
Can you please test and get back to me.

https://github.com/octavenz/silverstripe-reoako/releases/tag/1.0.0

**Comment by Sitetools** [comment]
Sorry for the slow response.
All good from our testing.
Thank you for the quick turn around.
