### ISSUE TITLE
Extra space each time page is saved

### ISSUE THREAD

**Issue by Sitetools** [octavenz/silverstripe-reoako#12]
Hi @octdanb,
If I highlight a word and add reoako to that word I get an extra space to the right of the highlighted word.
I can correct it then save it, I get an extra space, if I save it again I then have two extra spaces to the right.
![image](https://github.com/octavenz/silverstripe-reoako/assets/8812656/44841245-06df-4045-9910-550c0708d136)
![image](https://github.com/octavenz/silverstripe-reoako/assets/8812656/dc9ee321-46bf-4081-a6fa-36fb11001ffe)
![image](https://github.com/octavenz/silverstripe-reoako/assets/8812656/e905e694-9673-4822-8641-ff025872ca63)

This also affects the front end 
![image](https://github.com/octavenz/silverstripe-reoako/assets/8812656/a9f7b5fe-84fc-4e2e-8604-a6632bb9674c)

Cheers

**Comment by octdanb** [comment]
Which version of the plugin are you running? We issued a fix for this a few weeks back

**Comment by Sitetools** [comment]
@octdanb we pulled the latest version with our monthly patches today, and you are correct, the issue was resolved.
Thank you.

**Comment by Sitetools** [comment]
Issue closed
