### ISSUE TITLE
$results can be object

### ISSUE THREAD

**Issue by leochenftw** [octavenz/silverstripe-reoako#3]
https://github.com/octavenz/silverstripe-reoako/blob/5a88b597f04a8bc24b0632b71db7adc72e1d78a7/code/controllers/ReoakoController.php#L46

This line will throw error if the `search` function in `ReoakoController` has captured errors

```
(object) array(
   'message' => 'Origin not allowed for token',
)
```
## Way to reproduce
1. Use a domain name that is not whitelisted (or for some reason not whitelisted but supposed to be 🙃)
2. Set your environment to `dev` (or you are not going to see the error message)
3. Go to any WYSIWYG editor
4. Highlight some text
5. Click the "R" button
6. Then you will see

So, you may want to update this line in your `catch` block to be 
```
$json = json_decode($response_info, true);
if (isset($json['message'])) {
    return $json;
}
```
this will unify the return type

https://github.com/octavenz/silverstripe-reoako/blob/5a88b597f04a8bc24b0632b71db7adc72e1d78a7/code/client/ReoakoClient.php#L118

and by the way, this line:
https://github.com/octavenz/silverstripe-reoako/blob/5a88b597f04a8bc24b0632b71db7adc72e1d78a7/code/client/ReoakoClient.php#L122

missing a "\\" in front of `Exception` (for this class is namespaced, it needs to escape the scope)
```
} catch (\Exception $e) {
```

**Comment by jghazally** [comment]
Hey @leochenftw, 
Thanks so much for the detailed issue reporting. 
Any chance you'd be keen on putting together a PR that we can roll in?
