### ISSUE TITLE
Guzzle 7 compatibility

### ISSUE THREAD

**Issue by mandrew** [octavenz/silverstripe-reoako#5]
Hello! Just installing your module and having a bit of issue with guzzle versions. We have just upgraded to Silverstripe 4.11, framework and graphql (4) require guzzle ^7.3, however your module requires 6.5.

I'm installed it on my local environment with 7 (https://github.com/mandrew/silverstripe-reoako/tree/guzzle7), so far so good! Just raising it as an issue for visibility.

**Comment by mandrew** [comment]
Raised a pull request for this https://github.com/octavenz/silverstripe-reoako/pull/6

**Comment by octdanb** [comment]
issue resolved with 0.2.0 release
